make: dSet.h dSet.cpp dUSet.h dUSet.cpp dynamicbag.h dynamicbag.cpp main.cpp
	 g++ dSet.h dSet.cpp dUSet.cpp dUSet.h dynamicbag.cpp dynamicbag.h main.cpp
make2: dUSet.h dUSet.cpp dynamicbag.cpp dynamicbag.h main.cpp
	 g++ dUSet.cpp dUSet.h dynamicbag.cpp dynamicbag.h main.cpp
